using System.CodeDom.Compiler;
using System.Text;
using Envied.SourceGenerator.Models.TypeInfo;
using Microsoft.CodeAnalysis;

namespace Envied.SourceGenerator;

internal partial class EnviedSourceGenerator
{
    private static string GenerateSource(ClassInfo classInfo, bool supportsPartial)
    {
        StringBuilder sb = new();
        using StringWriter writer = new(sb);
        using IndentedTextWriter source = new(writer, "\t");

        WriteNamespaceAndUsings(source, classInfo);
        WriteClassDeclaration(source, classInfo, supportsPartial);
        return sb.ToString();
    }

    private static void WriteNamespaceAndUsings(IndentedTextWriter source, ClassInfo classInfo)
    {
        source.WriteLine("using Envied.Utils;");
        source.WriteLine("using System.Reflection;");
        source.WriteLine($"namespace {classInfo.Namespace};");
    }

    private static void WriteClassDeclaration(
        IndentedTextWriter source,
        ClassInfo classInfo,
        bool supportsPartial
    )
    {
        if (
            !classInfo.Modifiers.Contains("static")
            && supportsPartial
            && !classInfo.Modifiers.Contains("partial")
        )
        {
            return;
        }

        WriteGeneratedComments(source);
        var modifiers = string.Join(" ", classInfo.Modifiers);
        source.WriteLine(
            supportsPartial
                ? $"{modifiers} class {classInfo.Name} "
                : $"{modifiers} class {classInfo.Name}_Generated "
        );
        source.WriteLine("{");
        source.Indent++;
        WriteBody(source, classInfo, supportsPartial);
    }

    private static void WriteBody(
        IndentedTextWriter source,
        ClassInfo classInfo,
        bool supportsPartial
    )
    {
        if (classInfo == ClassInfo.Empty)
            return;

        Console.WriteLine($"Generating fields for {classInfo.Name}...");
        bool needsKey = false;

        if (classInfo.Properties.Length == 0)
            return;

        foreach (var propertyInfo in classInfo.Properties)
        {
            Console.WriteLine(
                $"Property {propertyInfo.Name} is {(propertyInfo.IsObfuscated ? "obfuscated" : "not obfuscated")}."
            );
            if (propertyInfo.IsObfuscated)
                needsKey = true;

            WriteMember(source, propertyInfo, supportsPartial);
        }

        if (needsKey)
        {
            WriteGeneratedComments(source);
            source.WriteLine(
                "private static readonly byte[] _key = RuntimeKeyHelper.DeriveKey(Assembly.GetCallingAssembly());"
            );
            source.WriteLine();
        }

        source.Indent--;
        source.WriteLine("}");
    }

    private static void WriteGeneratedComments(IndentedTextWriter source)
    {
        source.WriteLine("// <auto-generated/>");
        source.WriteLine("#nullable enable");
    }

    private static void WriteMember(
        IndentedTextWriter source,
        PropertyInfo property,
        bool supportsPartial
    )
    {
        if (
            !property.Modifiers.Contains("static")
            && supportsPartial
            && !property.Modifiers.Contains("partial")
        )
        {
            return;
        }

        var privateField = $"_{property.Name.ToLower()}";
        WriteGeneratedComments(source);

        source.WriteLine($"private static {property.Type.Name} {privateField} = {property.Value};");
        source.WriteLine();

        WriteGeneratedComments(source);
        source.WriteLine(
            $"{string.Join(" ", property.Modifiers)} {property.Type.Name} {property.Name} => {privateField};"
        );
        source.WriteLine();
    }
}
