<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Envied.SourceGenerator.Analyzer</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Envied.SourceGenerator</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all">
      <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="dotenv.net" PrivateAssets="all" />
  </ItemGroup>
</Project>