using System.CodeDom.Compiler;
using System.Reflection;
using System.Text;
using Envied.SourceGenerator.Models;
using Envied.SourceGenerator.Models.TypeInfo;
using PropertyInfo = Envied.SourceGenerator.Models.TypeInfo.PropertyInfo;

namespace Envied.SourceGenerator;

internal partial class EnviedSourceGenerator
{
    private static readonly string s_assemblyName;
    private static readonly string s_version;

    private static readonly Dictionary<string, string> _encryptedVars = [];

    static EnviedSourceGenerator()
    {
        var assembly = Assembly.GetAssembly(typeof(EnviedSourceGenerator));
        s_assemblyName = assembly?.GetCustomAttribute<AssemblyTitleAttribute>()?.Title ?? "Untitled";
        s_version = assembly?.GetCustomAttribute<AssemblyFileVersionAttribute>()?.Version ?? "0.0.0.0";
    }

    private static string GenerateSource(ClassInfo classInfo, bool supportsPartial)
    {
        StringBuilder sb = new();
        using StringWriter writer = new(sb);
        using IndentedTextWriter source = new(writer, "\t");

        WriteGeneratedComments(source);
        WriteNamespaceAndUsings(source, classInfo);
        WriteClassDeclaration(source, classInfo, supportsPartial);
        return sb.ToString();
    }

    private static void WriteNamespaceAndUsings(IndentedTextWriter source, ClassInfo classInfo)
    {
        source.WriteLine("using Envied.Utils;");
        source.WriteLine("using System.Reflection;");
        source.WriteLine($"namespace {classInfo.Namespace};");
        source.WriteLine();
    }

    private static void WriteClassDeclaration(
        IndentedTextWriter source,
        ClassInfo classInfo,
        bool supportsPartial
    )
    {
        if (
            !classInfo.Modifiers.Contains("static")
            && supportsPartial
            && !classInfo.Modifiers.Contains("partial")
        )
            return;

        WriteGeneratedAttributes(source);
        var modifiers = string.Join(" ", classInfo.Modifiers);
        source.WriteLine(
            supportsPartial
                ? $"{modifiers} class {classInfo.Name} "
                : $"{modifiers} class {classInfo.Name}_Generated "
        );
        source.WriteLine("{");
        source.Indent++;
        WriteBody(source, classInfo, supportsPartial);
    }

    private static void WriteBody(
        IndentedTextWriter source,
        ClassInfo classInfo,
        bool supportsPartial
    )
    {
        if (classInfo == ClassInfo.Empty)
            return;

        Console.WriteLine($"Generating fields for {classInfo.Name}...");

        if (classInfo.Properties.Length == 0)
            return;

        WriteGetAndSetMethod(source, classInfo.Properties);
        foreach (var property in classInfo.Properties)
        {
            WriteMember(source, property, supportsPartial);
        }

        source.Indent--;
        source.WriteLine("}");
    }

    private static void WriteGetAndSetMethod(IndentedTextWriter source, ValueEquatableArray<PropertyInfo> props)
    {
        source.WriteLine("private static readonly Dictionary<string, object> _envValues = new() {");
        source.Indent++;
        foreach (var propertyInfo in props)
        {
            if (propertyInfo.IsObfuscated)
            {
                _encryptedVars.Add(propertyInfo.Name, propertyInfo.Value);
                continue;
            }

            source.WriteLine($"{{\"{propertyInfo.Name}\", {propertyInfo.Value}}},");
        }
        source.Indent--;
        source.WriteLine("};");
        source.WriteLine();

        source.WriteLine("public static T GetValue<T>(string name) =>");
        source.WriteLine("    _envValues[name] is T value ? value : throw new KeyNotFoundException();");
        source.WriteLine();

        source.WriteLine("public static void SetValue<T>(string name, T value, bool encrypt) =>");
        source.WriteLine("    _envValues[name] = encrypt ? EncryptHelper.Encrypt(value) : value;");
        source.WriteLine();
    }

    private static void WriteGeneratedComments(IndentedTextWriter source)
    {
        source.WriteLine(" // -----------------------------------------------------------------------------");
        source.WriteLine(" // <auto-generated>");
        source.WriteLine($" //    This file was automatically generated by {s_assemblyName}, Version: {s_version}.");
        source.WriteLine(" //    Changes to this file may cause incorrect behavior and will be lost if");
        source.WriteLine(" //    the code is regenerated.");
        source.WriteLine(" // </auto-generated>");
        source.WriteLine(" // -----------------------------------------------------------------------------");
        source.WriteLine();
    }

    private static void WriteGeneratedAttributes(IndentedTextWriter source)
    {
        source.WriteLine($"[System.CodeDom.Compiler.GeneratedCodeAttribute(\"{s_assemblyName}\", \"{s_version}\")]");
        source.WriteLine("[System.Diagnostics.DebuggerNonUserCodeAttribute]");
        source.WriteLine("[System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        source.WriteLine();
    }

    private static void WriteMember(
        IndentedTextWriter source,
        PropertyInfo property,
        bool supportsPartial
    )
    {
        if (
            !property.Modifiers.Contains("static")
            && supportsPartial
            && !property.Modifiers.Contains("partial")
        )
        {
            return;
        }

        var privateField = $"_{property.Name.ToLower()}";
        source.WriteLine($"private static {property.Type.Name} {privateField} = {(property.IsObfuscated ? $"EnvHelper.GetValue(\"{property.Name}\", GetValue, (v) => SetValue(\"{property.Name}\", v))" : $"GetValue<{property.Type.Name}>(\"{property.Name}\")")};");
        source.WriteLine();

        source.WriteLine(
            $"{string.Join(" ", property.Modifiers)} {property.Type.Name} {property.Name} => {(property.IsObfuscated ? $"EncryptHelper.Decrypt({privateField})" : privateField)};"
        );
        source.WriteLine();
    }

    private static string GenerateHelpers()
    {
        StringBuilder sb = new();
        using StringWriter writer = new(sb);
        using IndentedTextWriter source = new(writer, "\t");

        WriteGeneratedComments(source);
        source.WriteLine("using Envied.Utils;");
        source.WriteLine("using System.Reflection;");
        source.WriteLine($"namespace {classInfo.Namespace};");
        source.WriteLine();

        source.WriteLine("public static class EnvHelper");
        source.WriteLine("{");
        source.Indent++;

        // Add methods for GetValue and SetValue here

        source.Indent--;
        source.WriteLine("}");

        return sb.ToString();
    }
}
