<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Envied.SourceGenerator.Analyzer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Envied.SourceGenerator.Analyzer\Envied.SourceGenerator.Analyzer.csproj" />
  </ItemGroup>
</Project>